# Matrix

## Matrix Calculation

### Dot product and Elemnt-wise calculation

내적(dot procuct)의 원소별(element-wise) 연산 : 내적은 두 벡터의 각 원의 곱을 모두 더해서 구함
element-wise 내적은 두 행렬 또는 벡터의 각 원소까지 이루어짐

In [3]:
import numpy as np 

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

dot_product = np.dot(a, b)
elementwise_product = a * b

print("Vector a:", a)
print("\nVector b:", b)

print("\n", a[0]*b[0], "+", a[1]*b[1], "+", a[2]*b[2])
print("Dot product of a and b:", dot_product)

print("\nElement-wise product of a and b:", elementwise_product)

Vector a: [1 2 3]

Vector b: [4 5 6]

 4 + 10 + 18
Dot product of a and b: 32

Element-wise product of a and b: [ 4 10 18]


행렬 곱셈(matrix multiplication): 행렬 곱셈은 많은 추천 시스템 알고리즘에서 필수적인 연산, 첫 번째 행렬의 행 원소에 두 번째 행렬의 열 원소를 곱하고 그 결과를 합산하는 element-wise 내적의 반족임

In [4]:
# Define the 2x2 matrices
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

# Calculate the result matrix by matrix multiplication
C = np.matmul(A, B)

# Show the calculator of each element in the result matrix
print("Matrix A")
print(A)

print("Matrix B")
print(B)

print("\nC[0, 0] = A[0, 0] * B[0, 0] + A[0, 1] * B[1, 0] = (1 * 5) + (2 * 7) =", 1*5 +2*7)
print("C[0, 1] = A[0, 0] * B[0, 1] + A[0, 1] * B[1. 1] = (1 * 6) + (2 * 8) =", 1*6 + 2*8)
print("C[1, 0] = A[1, 0] * B[0, 0] + A[1, 1] * B[1, 0] = (3 * 5) + (4 * 7) =", 3*5 + 4*7)
print("C[1, 1] = A[1, 0] * B[0, 1] + A[1, 1] * B[1, 1] = (3 * 6) + (4 * 8) =", 3*6 + 4*8)

print("\nResult Matrix C:")
print(C)

Matrix A
[[1 2]
 [3 4]]
Matrix B
[[5 6]
 [7 8]]

C[0, 0] = A[0, 0] * B[0, 0] + A[0, 1] * B[1, 0] = (1 * 5) + (2 * 7) = 19
C[0, 1] = A[0, 0] * B[0, 1] + A[0, 1] * B[1. 1] = (1 * 6) + (2 * 8) = 22
C[1, 0] = A[1, 0] * B[0, 0] + A[1, 1] * B[1, 0] = (3 * 5) + (4 * 7) = 43
C[1, 1] = A[1, 0] * B[0, 1] + A[1, 1] * B[1, 1] = (3 * 6) + (4 * 8) = 50

Result Matrix C:
[[19 22]
 [43 50]]


### Transpose Matrix

행렬의 전치 : 행렬 전치는 단순히 행과 열을 바꾸어 주면 됨. 이 연산은 매우 단순하지만 자주 사용되는 작업으로, 추천 알고리즘에서는 대표적으로 MF, ALS 등에서 사용됨

In [5]:
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

A_transpose = np.transpose(A)
print("Matrix A:\n", A)
print("\nTranspose of A:\n", A_transpose)

Matrix A:
 [[1 2]
 [3 4]
 [5 6]]

Transpose of A:
 [[1 3 5]
 [2 4 6]]


In [6]:
A.T

array([[1, 3, 5],
       [2, 4, 6]])

### Inverse Matrix
행렬의 역행렬: 정사각형 행렬의 역행렬은 원 행렬에 곱하면 행렬의 단위 행렬이 나오는 행렬. 선형 시스템(연립 방정식)의 해을 구하는데 사용되거나, 추천에서는 SVD를 계산하는데 사용됨

In [7]:
A = np.array([[1, 2], 
              [3, 4]])

A_inverse = np.linalg.inv(A)
print("Matrix A:", A)
print("\nInverse of A:\n", A_inverse)
print("\nA * A_inverse (Indentity matrix):\n", np.matmul(A, A_inverse))

Matrix A: [[1 2]
 [3 4]]

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]

A * A_inverse (Indentity matrix):
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


### Diaginal Matrix

대각행렬 (diagonal matrix): 대각 행렬은 주 대각선 바깥으로 모든 요소가 0인 정사각형 행렬을 의미. 주 대각선은 행과 열 인덱스가 같은 원소로 구성됨. 대각선 행렬은 다양한 알고리즘에 사용되며 그 구조로 인해 계산을 단순화하는데 사용됨

In [9]:
D = np.diag([1, 2, 3])
print("Diagonal Matrix D:\n", D)

Diagonal Matrix D:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


### Eigenvector and Eigenvalue

고유값과 공유벡터 : 정사각형 행렬 A의 고유 벡터는 0이 아닌 벡터로, A를 곱하면 그 자체의 스칼라 배수가 되는 성질을 띰. 이 스칼라 배수 값을 고유값이라고 함

In [10]:
A = np.array([[1, 2],
              [3, 4]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Matrix A:\n", A)
print("\nEigenvalues of A:\n", eigenvalues)
print("\nEigenvectors of A:\n", eigenvectors)

Matrix A:
 [[1 2]
 [3 4]]

Eigenvalues of A:
 [-0.37228132  5.37228132]

Eigenvectors of A:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


### Rank

랭크 행렬: 행렬의 행렬계수는 행렬에서 선형적으로 독립적인 열 벡터(또는 행 벡터)의 최대 개수, 기하학적으로는 단위벡터에 한 선형 변환이 가해졌을 때 도착하는 공간의 차원 수

In [17]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

rank_A = np.linalg.matrix_rank(A)
print("Matrix A:\n", A)
print("\nRank of A:", rank_A)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Rank of A: 2


### SVD

특이값 분해 (SVD) : SVD는 행렬을 $U$, $\Sigma$(시그마), $V^T$($V$의 전치)의 세 행렬로 분해하는데 사용되는 기법으로, 여기서 $U$와 $V$는 직교 행렬이고 $\Sigma$는 특이값이 포함된 대각선 행렬임. SVD는 데이터의 차원을 줄이고, 노이즈를 제거하는데도 사용되며, 추천 시스템의 맥락에서는 Latent Factor를 발견하는데 사용할 수 있음

In [25]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

U, sigma, Vt = np.linalg.svd(A)

print('Matrix A:\n', A)
print('\nU:\n', U)
print('\nSingular values (sigma):\n', sigma)
print('\n V transpose (Vt):\n', Vt)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

U:
 [[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]

Singular values (sigma):
 [1.68481034e+01 1.06836951e+00 4.41842475e-16]

 V transpose (Vt):
 [[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]


In [26]:
Sigma = np.diag(sigma)
print('Diagonal matrix (Sigma):\n', Sigma)

Diagonal matrix (Sigma):
 [[1.68481034e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.06836951e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 4.41842475e-16]]


SVD 구성요소 ($U$, $\Sigma$, $V^T$)를 각각 곱하면, 원래 행렬 A를 재구성할 수 있음

In [27]:
reconstructed_A = np.matmul(np.matmul(U, Sigma), Vt)
print("Reconstructed Matrix A from SVD componetns:\n", reconstructed_A)

Reconstructed Matrix A from SVD componetns:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## 유사도 메트릭 (Similarity Metircs)

### Cosine Similarity and Euclidean distance

In [28]:
# compute Euclidean distance
def euclidean_distance(vec1, vec2):
    return np.sqrt(np.sum((vec1 - vec2) ** 2))

# compute Cosine distance
def cosine_distance(vec1, vec2):
    dot_product = np.dot(vec1, vec2)
    norm_a = np.linalg.norm(vec1)
    norm_b = np.linalg.norm(vec2)
    return 1 - (dot_product / (norm_a * norm_b))

$$\text{similarity}=\cos(\theta)=\frac{A\dot B}{\vert\vert A\vert\vert ||B||}=\frac{\sum_{i=1}^n A_iB_i}{\sqrt{\sum_{i=1}^n A_i^2}\sqrt{\sum_{i=1}^n B_i^2}}$$

아래 데이터프레임은 아래 3개의 문장을 단어별로 카운트해서 벡터로 만든 결과임

"I like apples.", "I like oranges", "I like apples. I really like apples."

In [29]:
import pandas as pd 
import numpy as np 

# create a pandas DataFrame with the word vectors
data = {'I': [1, 1, 2], 'like': [1, 1, 2], 'apples': [1, 0, 2], 'oranges': [0, 1, 1], 'really': [0, 0, 1]}
df = pd.DataFrame(data)
df.index = [1, 2, 3]

display(df)

I  like  apples  oranges  really
1  1     1       1        0       0
2  1     1       0        1       0
3  2     2       2        1       1

문장 1과 문장 2는 동일한 구성을 갖는 대신 단어가 한 개 다름 (apples -> oranges)

문장 1과 문자 2 사이의 코사인 거리는 0.33으로, 벡터 방향에 약간의 차이가 있음을 시사함, 문장1과 문장2 사이의 유클리드 거리는 1.414로 단어 한개가 다른 영향을 보여줌

반면에 문장 1과 문장 3 사이의 유클리드 거리는 2보다 크며, 이는 두 문장 간의 차이가 있음을 나타탬, 이는 유클리는 거리는 방향 뿐만 아니라 크기에도 영향을 받음을 보여줌

In [37]:
sentence1_vector = df.iloc[0].values
sentence2_vector = df.iloc[1].values
sentence3_vector = df.iloc[2].values

euclidean_dist_12 = euclidean_distance(sentence1_vector, sentence2_vector)
cosine_dist_12 = cosine_distance(sentence1_vector, sentence2_vector)

euclidean_dist_13 = euclidean_distance(sentence1_vector, sentence3_vector)
cosine_dist_13 = cosine_distance(sentence1_vector, sentence3_vector)

print(f"Euclidean distance between sentence 1 and sentence 2: {euclidean_dist_12}")
print(f"Cosine distance between sentence 1 and sentence 2: {cosine_dist_12}")

print(f"Euclidean distance betwen sentence 1 and sentence 3: {euclidean_dist_13}")
print(f"Cosine distance between sentence 1 and sentence 3: {cosine_dist_13}")

Euclidean distance between sentence 1 and sentence 2: 1.4142135623730951
Cosine distance between sentence 1 and sentence 2: 0.33333333333333326
Euclidean distance betwen sentence 1 and sentence 3: 2.23606797749979
Cosine distance between sentence 1 and sentence 3: 0.07417990022744847
